### PR TITLE
Added .gitignore file

### PR DESCRIPTION
**Pull request by tmair**
I added a .gitignore file that excludes the various `node_modules` directories and `npm-debug.log` files

### CODE REVIEW

**Comment by ghost** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by fkling** [comment]
Thanks! I probably have this setup in my global `.gitignore` file so this wasn't an issue for me 😏  .

I think the patterns could be simplified to

```
node_modules/
npm-debug.log
```

The `**/` are redundant according to https://git-scm.com/docs/gitignore

**Comment by ghost** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by tmair** [comment]
> I think the patterns could be simplified 

That is correct. I updated the pull request

**Comment by fkling** [comment]
Thank you!

**Pull request merged**
