### PR TITLE
Correct foundation-sites css path

### PR DESCRIPTION
**Pull request by hawkins**
I've installed exerslide but receive an error immediately after initializing and serving a new project/presentation. The error is as follows:

```
Change detected, updating presentation...
Presentation generation failed!
List of errors:
Cannot resolve module 'foundation-sites/dist/foundation.css'
```

Looks like `foundation-sites`'s css file has moved to `.../dist/css` instead of `.../dist`, so whatever is looking for `'foundation-sites/dist/foundation.css` should instead look for `foundation-sites/dist/css/foundation.css`. So, I've replaced every occurrence of the old path with the corrected path.

#### Error repro steps

0. `$ npm install -g exerslide-cli`
1. `$ mkdir error-test && cd error-test`
2. `$ exerslide init`
3. `$ exerslide serve`

#### Help request

That being said, I'm new to both exerslide and large scaffolding projects like this, so I couldn't figure out how to point exerslide-cli to use the modified code to test that my 'fix' truly fixes the issue when initializing a new presentation. :fearful: Manually making the changes in a newly initialized project did correct the error, however, so I suspect I haven't configured my dev environment correctly. 

~~Normally I would just make this an issue, but I'm really enjoying using exerslide so far and would love to contribute more, so could you help me understand how to test new features/bug fixes like this with the project's structure?~~ 

**Edit**: I've found your comment explaining the process for peer linking the packages on another issue, I'll test that ASAP tonight and report back.

### CODE REVIEW

**Comment by fkling** [comment]
Thank you for catching that! That shows that I haven't initialized a project in a while... I hope you still  enjoy exerslide (I'm very happy to hear that!), even though that part is now crossed out ;)

Just to repeat here: In order to initialize a test project for development, you can run `scripts/setupDevEnv.js someTestProject`. That will initialize a new presentation inside `someTestProject` and link all the packages for you. That means any changes made to them will automatically be reflected in the project. However, when you make changes to the some of the scaffolding files (i.e. the files that are copied into the project), you have to run `exerslide copy-defaults` inside the project folder.

Let me know if this works for you and I will merge the PR.

Thank you again, I really appreciate it!

**Comment by hawkins** [comment]
Haha, woops! Looks like I got a little overzealous on the strikethrough there! :stuck_out_tongue: 

Anyways, thanks for the recap, and that script worked fine and showed the issue has been fixed with my change as expected.

**Comment by fkling** [comment]
Great, thank you for fixing this! I'll try to create a new release tomorrow but can't promise anything (due to the holidays).

**Comment by fkling** [comment]
exerslide v1.1.4 was published!

**Pull request merged**
